### ISSUE TITLE
Support for case insensitive matching

### ISSUE THREAD

**Issue by peterlvilim** [dhamidi/tmenu#17]
I was interested in potentially implementing support for case insensitive matching.  For instance the edit example in the readme would be easier to use in a java repository where it is common to have mixed case filenames.

I believe this tool aims for UTF-8 compatibility.  Which means that you would need to support some way of converting cases in order to still support this.  IBM has a library devoted to this (IBM ICU) however it is written in c++ which seems like a weighty dependency for this type of project.

Another possibility would be to just use a conversion method that only works for the english alphabet and say that the case insensitive option can only be used in that case.

Issue #5 makes note of using iconv to do the conversion.  I assume this means that you would be open to using an external tool.  So one potential option would be to use popen in conjunction with sed to do the conversion.  I believe that this would not decrease the target install base.

http://stackoverflow.com/questions/3785375/how-to-convert-text-file-to-lowercase-in-unix-but-in-utf-8

If latency were too slow for popen (popen can only be read or written which means it would have to be fired on every user keystroke) then it might be possible to open a pipe that can be both read and written since sed is a stream processor.  I would need to research this more. 

Would be happy to write a diff for this.  But since there are several options I thought I would open an issue first.

**Comment by dhamidi** [comment]
Hey @peterlvilim,

thank you for taking the time and filing an issue.  I'm sorry for not having replied earlier, at the moment I'm very busy with projects that are not related to computers.  The easiest way for you to get case insensitive matching right now is to normalize (e.g. lowercase) the input before passing it to tmenu.  Perl is installed on a lot of systems and has good Unicode support out of the box, so the easiest would be something along the lines of:

```sh
|perl -CSA -ne 'chomp; print lc . " $_\n";' | tmenu | sed 's/^[[:alnum]]* //'
```

This prepends a lowercase version of all input strings to each line (for matching purposes) and deletes it again from the output.  The options `-CSA` treat `STDIN`, `STDOUT` and `STDERR` and values of `@ARGV` as UTF-8 encoded strings.

> Issue #5 makes note of using iconv to do the conversion. I assume this means that you would be open to using an external tool.

Actually the ticket is meant to add support for the iconv C-API: http://pubs.opengroup.org/onlinepubs/9699919799/functions/iconv.html

I believe that having `tmenu` internally use other programs leads to complex dependencies (e.g tmenu not functioning properly because the `popen`'ed file is not executable by the current user).  If it can be avoided `tmenu` should not communicate internally with other programs.

> Would be happy to write a diff for this.

Feel free to add `iconv(3)` support :-)

> But since there are several options I thought I would open an issue first.

Thank you for your consideration and patience!

**Comment by peterlvilim** [comment]
Thanks for the detailed response.  Not surprised you have that opinion on external dependencies.

The perl idea is great, and I will give that try.

I'll take a look at iconv when I get a chance.

**Comment by dhamidi** [comment]
> The perl idea is great, and I will give that try.

I'm very glad to hear that.  Hopefully it works for your use case!

> I'll take a look at iconv when I get a chance.

Thank you!
